#date 757383048
^\0E   The Galactic Times                                        ^\0731-Dec-1993
#date 757383048
^\09___________________________________________________________________________
#date 757383048

#date 757383048
^\01Ä^\09Ä^\03Ä^\0BÄ^\07^\07The game was reset.                                                    

