[sdl]
fullscreen=false
output=surface
autolock=false
windowresolution=640x480

[dosbox]
machine=svga_s3
memsize=64

[cpu]
core=auto
cputype=auto
cycles=max

[dos]
xms=true
ems=true
umb=true

[autoexec]
mount c /home/nick/Projects/Code_Projects/orbitbbs
c:
set PATH=C:\BCPP31\BIN
set TEMP=C:\TEMP
mkdir TEMP
cd wwivs424
make -f makefile.mak
exit
