[1;36m==============================================================================

  [1;33m ллллллЛ ллллллЛ ллллллЛ ллЛллллллллЛллллллЛ ллллллЛ лллллллЛ
  [1;33mллЩЭЭЭллЛллЩЭЭллЛллЩЭЭллЛллКШЭЭллЩЭЭМллЩЭЭллЛллЩЭЭллЛллЩЭЭЭЭМ
  [1;33mллК   ллКллллллЩМллллллЩМллК   ллК   ллллллЩМллллллЩМлллллллЛ
  [1;33mллК   ллКллЩЭЭллЛллЩЭЭллЛллК   ллК   ллЩЭЭллЛллЩЭЭллЛШЭЭЭЭллК
  [1;33mШллллллЩМллК  ллКллллллЩМллК   ллК   ллллллЩМллллллЩМлллллллК
  [1;33m ШЭЭЭЭЭМ ШЭМ  ШЭМШЭЭЭЭЭМ ШЭМ   ШЭМ   ШЭЭЭЭЭМ ШЭЭЭЭЭМ ШЭЭЭЭЭЭМ

  [1;36m==============================================================================

  [1;32mWelcome to OrbitBBS![0m  A retro BBS for the modern small web.

  [1;37mFeeds[0m    Hacker News њ Lobsters њ Geminispace
  [1;37mDiscuss[0m  Tech њ Retro Computing њ Small Web
  [1;37mConnect[0m  telnet port 2323

  [1;36m==============================================================================[0m

