                   WWIV Software Services
                      P.O. Box 720455
                     McAllen, Tx 78504

Name___________________________________

Address________________________________

       ________________________________

BBS Name (show EXACTLY as in INIT)_________________________

WWIV Registration Number (if registered)___________________


                                              QTY   AMOUNT
ESM       (External String Manager)   $5.00   ___   ______

UEDIT     (User Editor)              $20.00   ___   ______

PackScan  (NetWork2 Preprocessor)    $20.00   ___   ______

PUS       (PackScan Update System)
 (Must be registered for each
  network)                           $20.00   ___   ______

StrPop    (String Pop)               $15.00   ___   ______

SPU       (Sound Playback Utility)   $10.00   ___   ______

GDU       (Graphics Display Utility) $10.00   ___   ______

TAM       (Transfer Area Manager)    $20.00   ___   ______

ProbeLite (Network Utility)          $10.00   ___   ______

UTIL_PAK  (Utility Package)          $10.00   ___   ______

RR       (Russian Roulette)          $10.00   ___   ______

Topper   (Top Ten User Utility)      $10.00   ___   ______

WSSFDI   (WSS FrontDoor Installer)   $15.00   ___   ______

WWMON    (WWIV Instance Monitor)     $10.00   ___   ______

WUFF     (WWIV Uploader for FIDOnet
         Files) unlimited            $75.00   ___   ______

         (WWIV Uploader for FIDOnet
         Files) 50 dirs              $50.00   ___   ______

         (WWIV Uploader for FIDOnet
          Files) 25 dirs             $25.00   ___   ______

WWIV4.xx  WWIV registration          $80.00   ___   ______

WWIV Source Code update via MAIL
 (Registered Users only)
 Includes Source, latest Net software,
 String Files, Docs, and compiled version

_____360k   _____720k   _____1.2Mg   $10.00   ___   ______
Place an X by disk size

                         1.44Mg       $7.50   ___   ______

WWIV Upgrade Instances
     (include UPGRADE.FRM)       $variable    ___   ______

NetUp (must include Signed agreement. $300    ___   ______
       Contact WWIV Software Services
       for agreement)
                                             -------------
Totals
                                             =============
Please send check or money order.  Do not send cash.  Do
not send checks that are not drawn on US banks.  There is a
$15.00 charge for checks that are not honored.

