                    WWIV v4.xx Registration/Order Form
                        WWIV Software Services
                           P.O. Box 720455
                        McAllen, Tx 78504-0455

SEE READ.ME file regarding Payment Plan, type of Currency, etc.
SEE LICENSE.AGR regarding Licensing Agreement

  Your Name_____________________________

  If you are on a network or network(s) fill in the following:

  WWIVnet Node Number________     WWIVlink Node Number________

  IceNET Node Number________      FidoNet Address_____________

  Other Network Name__________________  Other Network Node_______

  Address_________________________________________City______________________

  State______________ Country___________________ Zip/Postal Zone____________

  BBS Phone Number___________________  Voice Phone__________________________

  Installment Plan (Y/N)________  (Circle One): Payment No. 1 2 3 4
  
  Complete this section ONLY if you intend to DOWNLOAD the source code
  from an authorized Source Distribution System (SDS).  A list of these
  is included with the WWIV documentation (see READ.ME).  ALL
  information below MUST BE COMPLETED for you to get the SDS access.

  User Name/Handle on SDS Site_______________________User Number_______

  SDS Node Number________ SDS BBS Name_________________________________
      
  NOTE:  Effective with v4.23 an explicit licensing agreement is in
  effect.  Registration means that you have read that license and
  agree to its terms.
                                             $/UNIT      QTY     Cost

  WWIV v4.xx registration                    $80        ______  $________
    (2 instances allowed)
  WWIV v4.xx installment plan                $20        ______  $________
    (3 payments at $20 and 1 at $25)
  Disk(s) mailed to North America            N/C        ______  $________
     (specify format below)
  Disk mailed outside North America          $5 each    ______  $________
     (specify format below)
    
                                                     SubTotal:  $________

  Sales Tax (7.75% of subtotal TEXAS residents only):           $________

  Total amount enclosed (check or money order only):            $________

  Disk Format is 1.44 on 3.5 inch diskettes.  If you cannot use that
  format, then (check one): ____360 ____720 ____1.2


