

                         WWIV Software Services
                            P.O. Box 720455
                         McAllen, Tx 78504-0455


                         UPGRADE CAPACITY FORM


Beginning with v4.23 of WWIV BBS software, the BBS will have "multi-
instance."  Multi-instance is defined to allow more than one "instance"
per user.lst.  An instance may be either a keyboard attached
to a computer or a comport attached to a remote modem.  Sysops who
are already registered are entitled to have two instances without
making any additional payment.  This form is for those who wish to
have more than two instances which utilize the same user.lst.

NAME:__________________________________  Registration Number___________

CURRENT MAILING  ADDRESS (Street or P.O. Box)__________________________

CURRENT CITY, STATE, ZIP ______________________________________________

Old Mailing Address (time of registration)_____________________________

Old City, State, Zip __________________________________________________

If you are on one or more of the following networks, please indicate
your node number.

WWIVnet_________  IceNET________  WWIVlink_______

Current Maximum Number of Instances______________________________

Maximum Number of Instances on this Order_________________________

                     P R I C I N G

    UpGrade From \ 1 or 2  4     8     16      32
    Upgrade To   :
               4 :  $20
               8 :  $45   $25
              16 :  $80   $60   $35
              32 : $120   $100  $75    $40
       unlimited : $220   $200  $175   $140   $100

     Amount from Above.......................................$ _________

     Sales Tax (Texas Residents only  .0775 * Amount) .......$ _________

     Total Enclosed..........................................$ _________

No credit cards or purchase orders accepted.  Payment must be by
personal check, cashier's check, or money order.  A $15.00 service
charge is levied on all returned checks.  For your protection, please
do not send cash.



