; -----------------------------------------------------------------------------
;
;                               WWIV Version 4
;                    Copyright (C) 1988-1994 by Wayne Bell
;
; -----------------------------------------------------------------------------
; Colors are selected numerically. To determine the value for a color, use the
; following chart:
;
;    0 = Black             8  = Dark Gray
;    1 = Blue              9  = Light Blue
;    2 = Green             10 = Light Green
;    3 = Cyan              11 = Light Cyan
;    4 = Red               12 = Light Red
;    5 = Magenta           13 = Light Magenta
;    6 = Brown             14 = Yellow
;    7 = Light Gray        15 = White
;
; Now, to calculate a color, you take the value for the background color and
; multiply by 16, then add it to the foreground color you wish. This will
; provide the value you should use for that color combination. Note that
: color values greater than 127 will result in blinking. In other words,
; you should probably restrict background colors to colors 0-7 above.
;
; An example: if you want to find the value for, say, bright yellow on magenta,
; it would be (5*16) + 14. This equates to (magenta * 16) + white.
;
; -----------------------------------------------------------------------------
;
; The various spawn options that may be used are:
;
; ABORT        Allows ^C to break the spwaned program.
; INTERNAL     Makes extern appear as part of BBS
; NOHANGUP     Doesn't check for hangup
; COMIO        Use RETURN.EXE for WWIV's DOS intercept (takes about 50k more mem)
; SHRINK       Swaps out to XMS, EMS, or disk, to free more memory.
; FILES        Creates STAT.WWV and RETURN.WWV files.
; NOPAUSE      Turns off user's pause-on-screen.
; NETPROG      Tries to run program in network data dir first.
; TOPSCREEN    Redraws topscreen after execution.
;
; These options may be combined like:
;
; SPAWNOPTS[FSED]=SHRINK,COMIO,NOHANGUP
;
; Valid locations that can have spawn options specified are:
;
; TIMED, NEWUSER, BEGINDAY, LOGON, ULCHK, FSED, PROT_SINGLE, PROT_BATCH
; CHAT, ARCH_E, ARCH_V, ARCH_A
;
; -----------------------------------------------------------------------------

[WWIV]
;
; Default spawn options
;
;SPAWNOPT[TIMED]        = SHRINK, FILES                 ; for timed event
;SPAWNOPT[NEWUSER]      = NONE                          ; for newuser event
;SPAWNOPT[BEGINDAY]     = SHRINK                        ; for beginday event
;SPAWNOPT[LOGON]        = COMIO                         ; for logon event
;SPAWNOPT[ULCHK]        = NOHUP, SHRINK                 ; for upload event
;SPAWNOPT[FSED]         = COMIO                         ; for FSEDs
;SPAWNOPT[PROT_SINGLE]  = NONE                          ; for single file xfers
;SPAWNOPT[PROT_BATCH]   = SHRINK, TOPSCREEN             ; for batch xfers
;SPAWNOPT[CHAT]         = SHRINK, FILES                 ; for wwivchat.exe
;SPAWNOPT[ARCH_E]       = COMIO, INTERNAL               ; for archive extraction
;SPAWNOPT[ARCH_V]       = COMIO, INTERNAL, ABORT        ; for viewing archives
;SPAWNOPT[ARCH_A]       = COMIO, INTERNAL               ; for adding to archives

;
; Newuser colors
;
;NUCOLOR[0]     = 7
;NUCOLOR[1]     = 11
;NUCOLOR[2]     = 14
;NUCOLOR[3]     = 5
;NUCOLOR[4]     = 31
;NUCOLOR[5]     = 2
;NUCOLOR[6]     = 12
;NUCOLOR[7]     = 9
;NUCOLOR[8]     = 6
;NUCOLOR[9]     = 3
;NUCOLORBW[0]   = 7
;NUCOLORBW[1]   = 15
;NUCOLORBW[2]   = 15
;NUCOLORBW[3]   = 15
;NUCOLORBW[4]   = 112
;NUCOLORBW[5]   = 15
;NUCOLORBW[6]   = 15
;NUCOLORBW[7]   = 7
;NUCOLORBW[8]   = 7
;NUCOLORBW[9]   = 7

;
; Colors
;
;TOPCOLOR       = 31                                    ; for topscreen info
;F1COLOR        = 31                                    ; for F1 user editor
;EDITLINECOLOR  = 112                                   ; current field in F1
;CHATSELCOLOR   = 95                                    ; for selecting sysop
;MSG_COLOR      = 3                                     ; for color msgs

;
; External program commandlines
;
;TERMINAL_CMD   =                                       ; external term prog
;EXECUTE_CMD    =                                       ; timed event
;UPLOAD_CMD     =                                       ; upload event
;BEGINDAY_CMD   =                                       ; beginday event
;NEWUSER_CMD    =                                       ; newuser event
;LOGON_CMD      =                                       ; logon event

;
; System specification
;
;SYSTEMNAME     =                                       ; BBS name
;SYSTEMPHONE    =                                       ; BBS phone #
;SYSOPNAME      =                                       ; sysop name

;
; RIP-specific constants
;
; The BBS ID should be all caps, and up to 9 chars
RIP_BBS_ID     = WWIV424
; If the user has RIP menus older than this date, a new set will be used.
; Note that you must use 2 digits for month, day, *and* year
RIP_MENU_DATE  = 03/03/95
; If pull-down menus don't align properly, adjust this offset:
RIP_ADJUST     = 0
; Path to RIP data files
RIP_DIR        = RIPMENUS

;
; System flags
; Un-comment out lines (remove leading semicolon) and set
; to Y or N for Yes or No
;
;FORCE_FBACK            =               ; force newusers to send fback
;CHECK_DUP_PHONES       =               ; check newuser dupe phones
;HANGUP_DUP_PHONES      =               ; hangup on newuser dupe phone
;POSTTIME_COMPENS       =               ; compensate for time posting
;USE_SIMPLE_ASV         =               ; simple auto-sysop-validation
;SHOW_HIER              =               ; show conf details in //je
;IDZ_DESC               =               ; 1st line of file_id.diz as descrip
;SETLDATE               =               ; set file date on nscan
;NEW_CHATSOUND          =               ; use different chat alarm
;SLASH_SZ               =               ; enable "/s" and "/z"
;READ_CD_IDZ            =               ; read file_id.diz from cdroms
;FSED_EXT_DESC          =               ; allow fsed for extended descriptions
;FAST_TAG_RELIST        =               ; don't show xfer dirs on tag relist
;MAIL_PROMPT            =               ; fancy mail prompt
;SHOW_CITY_ST           =               ; show city/state in laston info
;LOCAL_SYSOP            =               ; allow F-keys, space-f, etc
;2WAY_CHAT              =               ; 2-way local sysop chat
;OFF_HOOK               =               ; phone offhook when sysop on
;PRINTER                =               ; send sysoplog to printer also
;LOG_DOWNLOADS          =               ; send SSM to uploader on file DL
;CLOSE_XFER             =               ; disable transfer section
;ALL_UL_TO_SYSOP        =               ; all uploads go to sysop dir
;NO_EASY_DL             =               ; Disable WWIV4*.* DL ignorng time,ratio
;NEW_EXTRACT            =               ; extended sysop-extract email/posts
;FAST_SEARCH            =               ; quick check of dup uploads
;NET_CALLOUT            =               ; allow net callouts this instance
;FIDO_PROCESS           =               ; process fido packets this instance
;USER_REGISTRATION      =               ; allow account expirations
;MSG_TAG                =               ; sysop post/email taglines
;CHAIN_REG              =               ; user sponsoring of chains
;CAN_SAVE_SSM           =               ; allow saving of SSMs
;PACKSCAN_FREQ          =               ; process packscan SSM requests
;EXTRA_COLOR            =               ; extra color in BBS
;RIP_SUPPORT            =               ; enable RIP
;RIPDRIVE_ON            =               ; enable ripdrive
;BEEP_CHAT              =               ; alert sysop of chat requests
;TWO_COLOR_CHAT         =               ; dual color in non-2-way chat
;ALLOW_ALIASES          =               ; allow users to use aliases
;USE_LIST               =               ; use list.com to show sysoplog, etc
;FREE_PHONE             =               ; allow any format phone #
;EXTENDED_USERINFO      =               ; enable addr, etc info in userrec


;
; ASV values
;
;SIMPLE_ASV[SL]         =
;SIMPLE_ASV[DSL]        =
;SIMPLE_ASV[EXEMPT]     =
;SIMPLE_ASV[AR]         =
;SIMPLE_ASV[DAR]        =
;SIMPLE_ASV[RESTRICT]   =

;
; System tuning parameters
;
;MAX_BATCH              = 50            ; max # files in batch queue
;MAX_EXTEND_LINES       = 10            ; max # extended description lines
;MAX_CHAINS             = 50            ; max # external chains
;MAX_GFILESEC           = 32            ; max # gfile sections

;
; Misc stuff
;
;RATIO_REQ              =               ; up/download ratio required
;MAIL_WHO_LEN           = 35            ; name/title tradeoff in email summary
